import './globals.css';
import { TaskProvider } from './context/TaskProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap the entire app in TaskProvider so all pages/components can use TaskContext */}
        <TaskProvider>{children}</TaskProvider>
      </body>
    </html>
  );
}
